"""platforms profiles gigs

Revision ID: 0002
Revises: 0001
"""

import sqlalchemy as sa

from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("faq", sa.JSON(), nullable=False),
        sa.Column("requirements", sa.JSON(), nullable=False),
        sa.Column("gallery", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column(
            "status", sa.Enum("draft", "ready", "live", "paused", name="gigstatus"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gigs_user_id"), "gigs", ["user_id"], unique=False)
    op.create_table(
        "master_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("headline", sa.String(length=300), nullable=False),
        sa.Column("bio", sa.Text(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("languages", sa.JSON(), nullable=False),
        sa.Column("hourly_rate", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("availability", sa.String(length=100), nullable=False),
        sa.Column("certifications", sa.JSON(), nullable=False),
        sa.Column("education", sa.JSON(), nullable=False),
        sa.Column("experience", sa.JSON(), nullable=False),
        sa.Column("contact_enc", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_master_profiles_user_id"), "master_profiles", ["user_id"], unique=True)
    op.create_table(
        "platform_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("profile_url", sa.String(length=500), nullable=False),
        sa.Column(
            "mode", sa.Enum("api", "email", "manual", name="integrationmode"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "connected", "error", "disconnected", name="accountstatus"),
            nullable=False,
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_platform_accounts_platform"), "platform_accounts", ["platform"], unique=False
    )
    op.create_index(
        op.f("ix_platform_accounts_user_id"), "platform_accounts", ["user_id"], unique=False
    )
    op.create_table(
        "portfolio_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_items_user_id"), "portfolio_items", ["user_id"], unique=False
    )
    op.create_table(
        "gig_packages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("gig_id", sa.Uuid(), nullable=False),
        sa.Column("tier", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("delivery_days", sa.Integer(), nullable=False),
        sa.Column("revisions", sa.Integer(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["gig_id"], ["gigs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gig_packages_gig_id"), "gig_packages", ["gig_id"], unique=False)
    op.create_table(
        "gig_platform_listings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("gig_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("overrides", sa.JSON(), nullable=False),
        sa.Column(
            "status", sa.Enum("draft", "ready", "live", "paused", name="gigstatus"), nullable=False
        ),
        sa.Column("external_url", sa.String(length=500), nullable=False),
        sa.Column("checklist", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["platform_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["gig_id"], ["gigs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gig_platform_listings_account_id"),
        "gig_platform_listings",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gig_platform_listings_gig_id"), "gig_platform_listings", ["gig_id"], unique=False
    )
    op.create_table(
        "integration_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("access_token_enc", sa.Text(), nullable=False),
        sa.Column("refresh_token_enc", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scopes", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["platform_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id"),
    )
    op.create_table(
        "platform_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("headline", sa.String(length=300), nullable=False),
        sa.Column("bio", sa.Text(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("hourly_rate", sa.Float(), nullable=True),
        sa.Column("synced_master", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["platform_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id"),
    )
    op.create_table(
        "sync_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["platform_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sync_logs_account_id"), "sync_logs", ["account_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sync_logs_account_id"), table_name="sync_logs")
    op.drop_table("sync_logs")
    op.drop_table("platform_profiles")
    op.drop_table("integration_tokens")
    op.drop_index(op.f("ix_gig_platform_listings_gig_id"), table_name="gig_platform_listings")
    op.drop_index(op.f("ix_gig_platform_listings_account_id"), table_name="gig_platform_listings")
    op.drop_table("gig_platform_listings")
    op.drop_index(op.f("ix_gig_packages_gig_id"), table_name="gig_packages")
    op.drop_table("gig_packages")
    op.drop_index(op.f("ix_portfolio_items_user_id"), table_name="portfolio_items")
    op.drop_table("portfolio_items")
    op.drop_index(op.f("ix_platform_accounts_user_id"), table_name="platform_accounts")
    op.drop_index(op.f("ix_platform_accounts_platform"), table_name="platform_accounts")
    op.drop_table("platform_accounts")
    op.drop_index(op.f("ix_master_profiles_user_id"), table_name="master_profiles")
    op.drop_table("master_profiles")
    op.drop_index(op.f("ix_gigs_user_id"), table_name="gigs")
    op.drop_table("gigs")
    # ### end Alembic commands ###
