"""inbox clients widget

Revision ID: 0004
Revises: 0003
"""

import sqlalchemy as sa

from alembic import op

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canned_responses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("shortcut", sa.String(length=40), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("canned_responses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_canned_responses_user_id"), ["user_id"], unique=False)

    op.create_table(
        "chat_widgets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("public_key", sa.String(length=40), nullable=False),
        sa.Column("greeting", sa.String(length=300), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_widgets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chat_widgets_public_key"), ["public_key"], unique=True)
        batch_op.create_index(batch_op.f("ix_chat_widgets_user_id"), ["user_id"], unique=True)

    op.create_table(
        "clients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("company", sa.String(length=200), nullable=False),
        sa.Column("country", sa.String(length=80), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("vip", sa.Boolean(), nullable=False),
        sa.Column("total_earned", sa.Float(), nullable=False),
        sa.Column("completed_orders", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_clients_user_id"), ["user_id"], unique=False)

    op.create_table(
        "client_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=40), nullable=False),
        sa.Column("handle", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "platform", "handle", name="uq_identity"),
    )
    with op.batch_alter_table("client_identities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_client_identities_client_id"), ["client_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_client_identities_user_id"), ["user_id"], unique=False)

    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=True),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("platform", sa.String(length=40), nullable=False),
        sa.Column("thread_key", sa.String(length=300), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("platform_url", sa.String(length=1000), nullable=False),
        sa.Column(
            "status", sa.Enum("open", "snoozed", "archived", name="convstatus"), nullable=False
        ),
        sa.Column("starred", sa.Boolean(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("snoozed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unread_count", sa.Integer(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_preview", sa.String(length=300), nullable=False),
        sa.Column("awaiting_reply_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("visitor_token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["platform_accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "platform", "thread_key", name="uq_thread"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversations_client_id"), ["client_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_conversations_last_message_at"), ["last_message_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_conversations_platform"), ["platform"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversations_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversations_user_id"), ["user_id"], unique=False)

    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.String(length=3), nullable=False),
        sa.Column("sender_name", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("delivery", sa.String(length=20), nullable=False),
        sa.Column("ai_generated", sa.Boolean(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("response_seconds", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "idempotency_key", name="uq_msg_idem"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_messages_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_messages_created_at"), ["created_at"], unique=False)

    op.create_table(
        "attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attachments_message_id"), ["message_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_attachments_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("client_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            "fk_jobs_client_id_clients", "clients", ["client_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint("fk_jobs_client_id_clients", type_="foreignkey")
        batch_op.drop_column("client_id")

    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attachments_user_id"))
        batch_op.drop_index(batch_op.f("ix_attachments_message_id"))

    op.drop_table("attachments")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_created_at"))
        batch_op.drop_index(batch_op.f("ix_messages_conversation_id"))

    op.drop_table("messages")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_user_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_status"))
        batch_op.drop_index(batch_op.f("ix_conversations_platform"))
        batch_op.drop_index(batch_op.f("ix_conversations_last_message_at"))
        batch_op.drop_index(batch_op.f("ix_conversations_client_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("client_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_client_identities_user_id"))
        batch_op.drop_index(batch_op.f("ix_client_identities_client_id"))

    op.drop_table("client_identities")
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clients_user_id"))

    op.drop_table("clients")
    with op.batch_alter_table("chat_widgets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_widgets_user_id"))
        batch_op.drop_index(batch_op.f("ix_chat_widgets_public_key"))

    op.drop_table("chat_widgets")
    with op.batch_alter_table("canned_responses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_canned_responses_user_id"))

    op.drop_table("canned_responses")
    # ### end Alembic commands ###
