"""notifications

Revision ID: 0005
Revises: 0004
"""

import sqlalchemy as sa

from alembic import op

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_addresses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("address", sa.String(length=200), nullable=False),
        sa.Column("opted_in", sa.Boolean(), nullable=False),
        sa.Column("link_code", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "channel", name="uq_channel"),
    )
    with op.batch_alter_table("channel_addresses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_channel_addresses_user_id"), ["user_id"], unique=False)

    op.create_table(
        "device_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token", name="uq_device_token"),
    )
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_device_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "notification_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dedupe_key", name="uq_notif_dedupe"),
    )
    with op.batch_alter_table("notification_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notification_events_type"), ["type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notification_events_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "event_type", "channel", name="uq_pref"),
    )
    with op.batch_alter_table("notification_preferences", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_preferences_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("provider_id", sa.String(length=200), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fallback_of", sa.Uuid(), nullable=True),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["notification_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_channel"), ["channel"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_event_id"), ["event_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_provider_id"), ["provider_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_user_id"))
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_status"))
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_provider_id"))
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_event_id"))
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_channel"))

    op.drop_table("notification_deliveries")
    with op.batch_alter_table("notification_preferences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_preferences_user_id"))

    op.drop_table("notification_preferences")
    with op.batch_alter_table("notification_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_notification_events_type"))
        batch_op.drop_index(batch_op.f("ix_notification_events_created_at"))

    op.drop_table("notification_events")
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_device_tokens_user_id"))

    op.drop_table("device_tokens")
    with op.batch_alter_table("channel_addresses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_addresses_user_id"))

    op.drop_table("channel_addresses")
    # ### end Alembic commands ###
