"""forms automations files

Revision ID: 0007
Revises: 0006
"""

import sqlalchemy as sa

from alembic import op

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automation_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("trigger", sa.String(length=40), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=False),
        sa.Column("actions", sa.JSON(), nullable=False),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("automation_rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_automation_rules_trigger"), ["trigger"], unique=False)
        batch_op.create_index(batch_op.f("ix_automation_rules_user_id"), ["user_id"], unique=False)

    op.create_table(
        "forms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("public_key", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("forms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_forms_public_key"), ["public_key"], unique=True)
        batch_op.create_index(batch_op.f("ix_forms_user_id"), ["user_id"], unique=False)

    op.create_table(
        "uploaded_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=True),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("uploaded_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_uploaded_files_user_id"), ["user_id"], unique=False)

    op.create_table(
        "automation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trigger", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("log", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["rule_id"], ["automation_rules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id", "dedupe_key", name="uq_run_dedupe"),
    )
    with op.batch_alter_table("automation_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_automation_runs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_automation_runs_rule_id"), ["rule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_automation_runs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "form_fields",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("type", sa.String(length=12), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("help_text", sa.String(length=500), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("show_if", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["form_id"], ["forms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("form_id", "key", name="uq_form_field_key"),
    )
    with op.batch_alter_table("form_fields", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_form_fields_form_id"), ["form_id"], unique=False)

    op.create_table(
        "form_submissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=True),
        sa.Column("submitter_name", sa.String(length=200), nullable=False),
        sa.Column("submitter_email", sa.String(length=320), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("signature", sa.JSON(), nullable=True),
        sa.Column("form_version", sa.Integer(), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["form_id"], ["forms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("form_submissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_form_submissions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_form_submissions_form_id"), ["form_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_form_submissions_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("form_submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_form_submissions_user_id"))
        batch_op.drop_index(batch_op.f("ix_form_submissions_form_id"))
        batch_op.drop_index(batch_op.f("ix_form_submissions_created_at"))

    op.drop_table("form_submissions")
    with op.batch_alter_table("form_fields", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_form_fields_form_id"))

    op.drop_table("form_fields")
    with op.batch_alter_table("automation_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automation_runs_user_id"))
        batch_op.drop_index(batch_op.f("ix_automation_runs_rule_id"))
        batch_op.drop_index(batch_op.f("ix_automation_runs_created_at"))

    op.drop_table("automation_runs")
    with op.batch_alter_table("uploaded_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploaded_files_user_id"))

    op.drop_table("uploaded_files")
    with op.batch_alter_table("forms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forms_user_id"))
        batch_op.drop_index(batch_op.f("ix_forms_public_key"))

    op.drop_table("forms")
    with op.batch_alter_table("automation_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automation_rules_user_id"))
        batch_op.drop_index(batch_op.f("ix_automation_rules_trigger"))

    op.drop_table("automation_rules")
    # ### end Alembic commands ###
